"""add compound cmp models

Revision ID: f84742b34aad
Revises:
Create Date: 2026-08-31 18:28:17.066714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import security_kit.crypto

# revision identifiers, used by Alembic.
revision: str = "f84742b34aad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compounds",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("ingredient_name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingredient_name"),
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("email_verification_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_email_verification_email_verified", ["email", "verified_at"], unique=False)

    op.create_table(
        "oauth_nonces",
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("nonce_hash"),
    )
    with op.batch_alter_table("oauth_nonces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_nonces_created_at"), ["created_at"], unique=False)

    op.create_table(
        "phone_verification_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("phone_verification_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_phone_verification_hash_verified", ["phone_hash", "verified_at"], unique=False)

    op.create_table(
        "sanctioned_identities",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sanctioned_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sanctioned_identities_phone_hash"), ["phone_hash"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("name", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("nickname", sa.String(length=12), nullable=False),
        sa.Column("phone_number", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("phone_hash", sa.String(length=64), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.Enum("M", "F", name="gender_enum"), nullable=True),
        sa.Column(
            "onboarding_status",
            sa.Enum("pending", "terms_agreed", "profile_required", "completed", name="onboarding_status_enum"),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_sanctioned", sa.Boolean(), nullable=False),
        sa.Column("sanction_reason", sa.String(length=500), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nickname"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_phone_hash"), ["phone_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_purge_at"), ["purge_at"], unique=False)

    op.create_table(
        "compound_evidences",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("compound_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("species", sa.String(length=10), nullable=False),
        sa.Column("component_key", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["compound_id"],
            ["compounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "compound_id", "species", "component_key", name="uq_compound_evidences_compound_species_component"
        ),
    )
    op.create_table(
        "compound_scores",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("compound_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("species", sa.String(length=10), nullable=False),
        sa.Column("risk_index", sa.Float(), nullable=True),
        sa.Column("risk_coverage", sa.Float(), nullable=False),
        sa.Column("opportunity_index", sa.Float(), nullable=True),
        sa.Column("opportunity_coverage", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["compound_id"],
            ["compounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("compound_id", "species", name="uq_compound_scores_compound_species"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("jti", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "social_accounts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "provider", sa.Enum("local", "google", "kakao", "naver", "apple", name="auth_provider_enum"), nullable=False
        ),
        sa.Column("provider_uid", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_uid", name="uq_social_provider_uid"),
    )
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_social_accounts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "species_alerts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("compound_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("species", sa.String(length=10), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["compound_id"],
            ["compounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "terms_agreements",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("terms_type", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "terms_type", name="uq_agreement_user_type"),
    )
    with op.batch_alter_table("terms_agreements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_terms_agreements_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("terms_agreements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_terms_agreements_user_id"))

    op.drop_table("terms_agreements")
    op.drop_table("species_alerts")
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_social_accounts_user_id"))

    op.drop_table("social_accounts")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))

    op.drop_table("refresh_tokens")
    op.drop_table("compound_scores")
    op.drop_table("compound_evidences")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_purge_at"))
        batch_op.drop_index(batch_op.f("ix_users_phone_hash"))

    op.drop_table("users")
    with op.batch_alter_table("sanctioned_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sanctioned_identities_phone_hash"))

    op.drop_table("sanctioned_identities")
    with op.batch_alter_table("phone_verification_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_phone_verification_hash_verified")

    op.drop_table("phone_verification_tokens")
    with op.batch_alter_table("oauth_nonces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_nonces_created_at"))

    op.drop_table("oauth_nonces")
    with op.batch_alter_table("email_verification_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_email_verification_email_verified")

    op.drop_table("email_verification_tokens")
    op.drop_table("compounds")
    # ### end Alembic commands ###
